name: Proxy Pool Update

on:
  schedule:
    - cron: '*/30 * * * *'  # 每30min运行一次
  workflow_dispatch:       # 支持手动触发

jobs:
  update-proxies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch proxies
        run: python scripts/fetch.py

      - name: Validate proxies
        run: python scripts/validate.py

      # 新增步骤：编译并运行generate.cpp生成Clash配置
      - name: Compile and run generate.cpp
        run: |
          # 编译C++文件（需要链接pthread库，因为使用了多线程）
          g++ scripts/generate.cpp -o generate -lpthread
          # 运行生成Clash配置
          ./generate

      - name: Commit and push changes
        run: |
          git config --global user.name 'FrankWkd-Pro[Bot]'
          git config --global user.email 'frankwkd@outlook.com'
          git add data/valid_ips.txt
          # 添加生成的Clash配置文件到提交
          git add data/clash_config.yaml
          git commit -m "[Bot] Update proxies and generate Clash config"
          git push
