name: Proxy Pool Update

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次
  workflow_dispatch:       # 支持手动触发

jobs:
  update-proxies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Fetch proxies
        run: python scripts/fetch.py

      - name: Validate proxies
        run: python scripts/validate.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'FrankWkd-Pro[Bot]'
          git config --global user.email 'frankwkd@outlook.com'
          git add data/valid_ips.txt
          git commit -m "Update valid proxies"
          git push
