name: Proxy Pool Update

on:
  schedule:
    - cron: '*/30 * * * *'  # 每30min运行一次
  workflow_dispatch:       # 支持手动触发

jobs:
  update-proxies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch proxies
        run: python scripts/fetch.py

      - name: Validate proxies
        run: python scripts/validate.py

      # 新增步骤：编译并运行generate.cpp
      - name: Compile and run generate.cpp
        run: |
          # 编译C++文件（使用g++，Ubuntu默认已安装）
          g++ scripts/generate.cpp -o generate
          # 执行编译后的程序
          ./generate

      - name: Commit and push changes
        run: |
          git config --global user.name 'FrankWkd-Pro[Bot]'
          git config --global user.email 'frankwkd@outlook.com'
          git add data/valid_ips.txt
          # 如果generate.cpp生成了其他需要提交的文件，需要在此处添加git add命令
          git commit -m "[Bot] Proxy IP Updated"
          git push
